--Q#8
SELECT PERSON.P_Name, PERSON.P_Phone
FROM OWNER
INNER JOIN PERSON ON OWNER.P_Ssn = PERSON.P_Ssn
INNER JOIN OWNS ON OWNER.O_ID = OWNS.OwnerID
WHERE OWNS.Pdate >= DATEADD(month, -1, GETDATE());